### ISSUE TITLE
Clause tree checkbox activated by enter key instead activates Expand tree button

### ISSUE THREAD

**Issue by NoahGresser** [aaact-aatia/a11y-ict-wizard#15]
In "Step 2: Refine clause selection", if a checkbox is given focus (such as by being clicked) and then the ENTER key is pressed, the "Expand tree" button's .click() function gets called instead of the checkbox being activated.

**Comment by ocelph** [comment]
This was fixed in the Edit Step 1 Tree checkbox structure
